version: '3'

services:
  postgresql:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: testapp
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./app:/symfony
    container_name: testapp-nginx
    restart: always
    ports:
      - "8080:80"

  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - ./app:/symfony
    container_name: testapp-php-fpm
    depends_on:
      - postgresql

  php-cli:
    build:
      context: ./docker/php-cli
    volumes:
      - ./app:/symfony
    command: sleep 10000
    container_name: testapp-php-cli

volumes:
  db-data:
